### ISSUE TITLE
fingerprint channel

### ISSUE THREAD

**Issue by RioRic** [keivanB/Clarkson_Finger_Gen#1]
Hi, Keivan, thanks for your nice work. Recently, I want to use stylegan2 to generate fingerprint, but the channels of fingerprint is 1, the channel of  the input in vgg needs  to be 3. How do you solve this problem?

**Comment by keivanB** [comment]
I converted all training samples into RGB. This is a well known trick for transfer learning with models train on RGB data.

**Comment by RioRic** [comment]
> I converted all training samples into RGB. This is a well known trick for transfer learning with models train on RGB data.

OK, thanks for your answer, I'll try it.
