### ISSUE TITLE
Google Colab not working

### ISSUE THREAD

**Issue by Znerual** [keivanB/Clarkson_Finger_Gen#2]
Dear KeivanB,

are you planning to release the tf2 update or is this repository no longer maintained? Unfortunately, the google colab does no longer work with tf 1.

**Comment by keivanB** [comment]
Hi, 

Thanks for reaching out, the repository is being maintained. I have been a bit busy with my day job lately. TF2 and possibly a PyTorch version will be coming in the next week. Additionally, several next-generation models will be released by next month.

**Comment by keivanB** [comment]
The collab code is not using Pytorch. Let me know if this is working for you. The code for our new model will be released soon with complete control over the generation process.

**Comment by Znerual** [comment]
Thank you for the update! The colab looks very good, looking forward to the next model
